In [1]:
import pandas as pd
import numpy as np
path = "D:/programs/grin/datasets/metr_la/metr_la.h5"
df = pd.read_hdf(path)

In [38]:
import datetime

# 输入的时间戳
timestamp = 1330560000000000000  # 假设是纳秒

# 将时间戳转换为日期时间
date_time = datetime.datetime.utcfromtimestamp(timestamp / 1e9)

# 打印日期时间
print(date_time)

2012-03-01 00:00:00

In [3]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [33]:
import h5py
with h5py.File(path,"r") as f:
    for key in f.keys():
        print(f[key], key, f[key].name)

<HDF5 group "/df" (4 members)> df /df

In [35]:

def print_hdf5_file_contents(group, indent=""):
    for name, item in group.items():
        if isinstance(item, h5py.Group):
            print(indent + f"Group: {name}")
            print_hdf5_file_contents(item, indent + "  ")
        elif isinstance(item, h5py.Dataset):
            print(indent + f"Dataset: {name}")
            print(indent + f"Shape: {item.shape}")
            # 如果数据集太大，可以选择打印部分数据，例如前几个元素
            # print(indent + "Data (partial):", item[:10])
        else:
            print(indent + f"Unknown item: {name}")

# 打开HDF5文件
file_path = path  # 替换成你的HDF5文件路径
h5_file = h5py.File(file_path, 'r')

# 调用递归函数来打印文件内容
print_hdf5_file_contents(h5_file)

# 关闭HDF5文件
h5_file.close()

Group: df
  Dataset: axis0
  Shape: (207,)
  Dataset: axis1
  Shape: (34272,)
  Dataset: block0_items
  Shape: (207,)
  Dataset: block0_values
  Shape: (34272, 207)

In [36]:
import h5py

def print_hdf5_file_contents(group, indent=""):
    for name, item in group.items():
        if isinstance(item, h5py.Group):
            print(indent + f"Group: {name}")
            print_hdf5_file_contents(item, indent + "  ")
        elif isinstance(item, h5py.Dataset):
            print(indent + f"Dataset: {name}")
            print(indent + f"Shape: {item.shape}")
            
            # 打印数据集的值
            if item.shape[0] < 10:  # 限制打印数据的行数，避免打印过多数据
                print(indent + "Data:")
                print(item[:])
            else:
                print(indent + "Data (partial):", item[:10])
        else:
            print(indent + f"Unknown item: {name}")

# 打开HDF5文件
file_path = path  # 替换成你的HDF5文件路径
h5_file = h5py.File(file_path, 'r')

# 调用递归函数来打印文件内容
print_hdf5_file_contents(h5_file)

# 关闭HDF5文件
h5_file.close()

Group: df
  Dataset: axis0
  Shape: (207,)
  Data (partial): [b'773869' b'767541' b'767542' b'717447' b'717446' b'717445' b'773062'
 b'767620' b'737529' b'717816']
  Dataset: axis1
  Shape: (34272,)
  Data (partial): [1330560000000000000 1330560300000000000 1330560600000000000
 1330560900000000000 1330561200000000000 1330561500000000000
 1330561800000000000 1330562100000000000 1330562400000000000
 1330562700000000000]
  Dataset: block0_items
  Shape: (207,)
  Data (partial): [b'773869' b'767541' b'767542' b'717447' b'717446' b'717445' b'773062'
 b'767620' b'737529' b'717816']
  Dataset: block0_values
  Shape: (34272, 207)
  Data (partial): [[64.375      67.625      67.125      ... 59.25       69.
  61.875     ]
 [62.66666667 68.55555556 65.44444444 ... 55.88888889 68.44444444
  62.875     ]
 [64.         63.75       60.         ... 61.375      69.85714286
  62.        ]
 ...
 [63.625      67.25       63.25       ... 52.         68.625
  59.375     ]
 [68.75       65.25       63.5        ... 48.625      67.625
  61.75      ]
 [63.5        61.5        62.5        ... 50.75       66.25
  62.25      ]]

In [6]:
for key in df.keys():
    print(key)

773869
767541
767542
717447
717446
717445
773062
767620
737529
717816
765604
767471
716339
773906
765273
716331
771667
716337
769953
769402
769403
769819
769405
716941
717578
716960
717804
767572
767573
773012
773013
764424
769388
716328
717819
769941
760987
718204
718045
769418
768066
772140
773927
760024
774012
774011
767609
769359
760650
716956
769831
761604
717495
716554
773953
767470
716955
764949
773954
767366
769444
773939
774067
769443
767750
767751
767610
773880
764766
717497
717490
717491
717492
717493
765176
717498
717499
765171
718064
718066
765164
769431
769430
717610
767053
767621
772596
772597
767350
767351
716571
773023
767585
773024
717483
718379
717481
717480
717486
764120
772151
718371
717489
717488
717818
718076
718072
767455
767454
761599
717099
773916
716968
769467
717576
717573
717572
717571
717570
764760
718089
769847
717608
767523
716942
718090
769867
717472
717473
759591
764781
765099
762329
716953
716951
767509
765182
769358
772513
716958
718496
769346
773904
718499
764853
761003
717502
759602
717504
763995
717508
765265
773996
773995
717469
717468
764106
717465
764794
717466
717461
717460
717463
717462
769345
716943
772669
717582
717583
717580
716949
717587
772178
717585
716939
768469
764101
767554
773975
773974
717510
717513
717825
767495
767494
717821
717823
717458
717459
769926
764858
717450
717452
717453
759772
717456
771673
772167
769372
774204
769806
717590
717592
717595
772168
718141
769373

In [7]:
key = df.keys()
key

Index(['773869', '767541', '767542', '717447', '717446', '717445', '773062',
       '767620', '737529', '717816',
       ...
       '772167', '769372', '774204', '769806', '717590', '717592', '717595',
       '772168', '718141', '769373'],
      dtype='object', length=207)

In [11]:
datetime_idx = sorted(df.index)
datetime_idx

[Timestamp('2012-03-01 00:00:00'),
 Timestamp('2012-03-01 00:05:00'),
 Timestamp('2012-03-01 00:10:00'),
 Timestamp('2012-03-01 00:15:00'),
 Timestamp('2012-03-01 00:20:00'),
 Timestamp('2012-03-01 00:25:00'),
 Timestamp('2012-03-01 00:30:00'),
 Timestamp('2012-03-01 00:35:00'),
 Timestamp('2012-03-01 00:40:00'),
 Timestamp('2012-03-01 00:45:00'),
 Timestamp('2012-03-01 00:50:00'),
 Timestamp('2012-03-01 00:55:00'),
 Timestamp('2012-03-01 01:00:00'),
 Timestamp('2012-03-01 01:05:00'),
 Timestamp('2012-03-01 01:10:00'),
 Timestamp('2012-03-01 01:15:00'),
 Timestamp('2012-03-01 01:20:00'),
 Timestamp('2012-03-01 01:25:00'),
 Timestamp('2012-03-01 01:30:00'),
 Timestamp('2012-03-01 01:35:00'),
 Timestamp('2012-03-01 01:40:00'),
 Timestamp('2012-03-01 01:45:00'),
 Timestamp('2012-03-01 01:50:00'),
 Timestamp('2012-03-01 01:55:00'),
 Timestamp('2012-03-01 02:00:00'),
 Timestamp('2012-03-01 02:05:00'),
 Timestamp('2012-03-01 02:10:00'),
 Timestamp('2012-03-01 02:15:00'),
 Timestamp('2012-03-01 02:20:00'),
 Timestamp('2012-03-01 02:25:00'),
 Timestamp('2012-03-01 02:30:00'),
 Timestamp('2012-03-01 02:35:00'),
 Timestamp('2012-03-01 02:40:00'),
 Timestamp('2012-03-01 02:45:00'),
 Timestamp('2012-03-01 02:50:00'),
 Timestamp('2012-03-01 02:55:00'),
 Timestamp('2012-03-01 03:00:00'),
 Timestamp('2012-03-01 03:05:00'),
 Timestamp('2012-03-01 03:10:00'),
 Timestamp('2012-03-01 03:15:00'),
 Timestamp('2012-03-01 03:20:00'),
 Timestamp('2012-03-01 03:25:00'),
 Timestamp('2012-03-01 03:30:00'),
 Timestamp('2012-03-01 03:35:00'),
 Timestamp('2012-03-01 03:40:00'),
 Timestamp('2012-03-01 03:45:00'),
 Timestamp('2012-03-01 03:50:00'),
 Timestamp('2012-03-01 03:55:00'),
 Timestamp('2012-03-01 04:00:00'),
 Timestamp('2012-03-01 04:05:00'),
 Timestamp('2012-03-01 04:10:00'),
 Timestamp('2012-03-01 04:15:00'),
 Timestamp('2012-03-01 04:20:00'),
 Timestamp('2012-03-01 04:25:00'),
 Timestamp('2012-03-01 04:30:00'),
 Timestamp('2012-03-01 04:35:00'),
 Timestamp('2012-03-01 04:40:00'),
 Timestamp('2012-03-01 04:45:00'),
 Timestamp('2012-03-01 04:50:00'),
 Timestamp('2012-03-01 04:55:00'),
 Timestamp('2012-03-01 05:00:00'),
 Timestamp('2012-03-01 05:05:00'),
 Timestamp('2012-03-01 05:10:00'),
 Timestamp('2012-03-01 05:15:00'),
 Timestamp('2012-03-01 05:20:00'),
 Timestamp('2012-03-01 05:25:00'),
 Timestamp('2012-03-01 05:30:00'),
 Timestamp('2012-03-01 05:35:00'),
 Timestamp('2012-03-01 05:40:00'),
 Timestamp('2012-03-01 05:45:00'),
 Timestamp('2012-03-01 05:50:00'),
 Timestamp('2012-03-01 05:55:00'),
 Timestamp('2012-03-01 06:00:00'),
 Timestamp('2012-03-01 06:05:00'),
 Timestamp('2012-03-01 06:10:00'),
 Timestamp('2012-03-01 06:15:00'),
 Timestamp('2012-03-01 06:20:00'),
 Timestamp('2012-03-01 06:25:00'),
 Timestamp('2012-03-01 06:30:00'),
 Timestamp('2012-03-01 06:35:00'),
 Timestamp('2012-03-01 06:40:00'),
 Timestamp('2012-03-01 06:45:00'),
 Timestamp('2012-03-01 06:50:00'),
 Timestamp('2012-03-01 06:55:00'),
 Timestamp('2012-03-01 07:00:00'),
 Timestamp('2012-03-01 07:05:00'),
 Timestamp('2012-03-01 07:10:00'),
 Timestamp('2012-03-01 07:15:00'),
 Timestamp('2012-03-01 07:20:00'),
 Timestamp('2012-03-01 07:25:00'),
 Timestamp('2012-03-01 07:30:00'),
 Timestamp('2012-03-01 07:35:00'),
 Timestamp('2012-03-01 07:40:00'),
 Timestamp('2012-03-01 07:45:00'),
 Timestamp('2012-03-01 07:50:00'),
 Timestamp('2012-03-01 07:55:00'),
 Timestamp('2012-03-01 08:00:00'),
 Timestamp('2012-03-01 08:05:00'),
 Timestamp('2012-03-01 08:10:00'),
 Timestamp('2012-03-01 08:15:00'),
 Timestamp('2012-03-01 08:20:00'),
 Timestamp('2012-03-01 08:25:00'),
 Timestamp('2012-03-01 08:30:00'),
 Timestamp('2012-03-01 08:35:00'),
 Timestamp('2012-03-01 08:40:00'),
 Timestamp('2012-03-01 08:45:00'),
 Timestamp('2012-03-01 08:50:00'),
 Timestamp('2012-03-01 08:55:00'),
 Timestamp('2012-03-01 09:00:00'),
 Timestamp('2012-03-01 09:05:00'),
 Timestamp('2012-03-01 09:10:00'),
 Timestamp('2012-03-01 09:15:00'),
 Timestamp('2012-03-01 09:20:00'),
 Timestamp('2012-03-01 09:25:00'),
 Timestamp('2012-03-01 09:30:00'),
 Timestamp('2012-03-01 09:35:00'),
 Timestamp('2012-03-01 09:40:00'),
 Timestamp('2012-03-01 09:45:00'),
 Timestamp('2012-03-01 09:50:00'),
 Timestamp('2012-03-01 09:55:00'),
 Timestamp('2012-03-01 10:00:00'),
 Timestamp('2012-03-01 10:05:00'),
 Timestamp('2012-03-01 10:10:00'),
 Timestamp('2012-03-01 10:15:00'),
 Timestamp('2012-03-01 10:20:00'),
 Timestamp('2012-03-01 10:25:00'),
 Timestamp('2012-03-01 10:30:00'),
 Timestamp('2012-03-01 10:35:00'),
 Timestamp('2012-03-01 10:40:00'),
 Timestamp('2012-03-01 10:45:00'),
 Timestamp('2012-03-01 10:50:00'),
 Timestamp('2012-03-01 10:55:00'),
 Timestamp('2012-03-01 11:00:00'),
 Timestamp('2012-03-01 11:05:00'),
 Timestamp('2012-03-01 11:10:00'),
 Timestamp('2012-03-01 11:15:00'),
 Timestamp('2012-03-01 11:20:00'),
 Timestamp('2012-03-01 11:25:00'),
 Timestamp('2012-03-01 11:30:00'),
 Timestamp('2012-03-01 11:35:00'),
 Timestamp('2012-03-01 11:40:00'),
 Timestamp('2012-03-01 11:45:00'),
 Timestamp('2012-03-01 11:50:00'),
 Timestamp('2012-03-01 11:55:00'),
 Timestamp('2012-03-01 12:00:00'),
 Timestamp('2012-03-01 12:05:00'),
 Timestamp('2012-03-01 12:10:00'),
 Timestamp('2012-03-01 12:15:00'),
 Timestamp('2012-03-01 12:20:00'),
 Timestamp('2012-03-01 12:25:00'),
 Timestamp('2012-03-01 12:30:00'),
 Timestamp('2012-03-01 12:35:00'),
 Timestamp('2012-03-01 12:40:00'),
 Timestamp('2012-03-01 12:45:00'),
 Timestamp('2012-03-01 12:50:00'),
 Timestamp('2012-03-01 12:55:00'),
 Timestamp('2012-03-01 13:00:00'),
 Timestamp('2012-03-01 13:05:00'),
 Timestamp('2012-03-01 13:10:00'),
 Timestamp('2012-03-01 13:15:00'),
 Timestamp('2012-03-01 13:20:00'),
 Timestamp('2012-03-01 13:25:00'),
 Timestamp('2012-03-01 13:30:00'),
 Timestamp('2012-03-01 13:35:00'),
 Timestamp('2012-03-01 13:40:00'),
 Timestamp('2012-03-01 13:45:00'),
 Timestamp('2012-03-01 13:50:00'),
 Timestamp('2012-03-01 13:55:00'),
 Timestamp('2012-03-01 14:00:00'),
 Timestamp('2012-03-01 14:05:00'),
 Timestamp('2012-03-01 14:10:00'),
 Timestamp('2012-03-01 14:15:00'),
 Timestamp('2012-03-01 14:20:00'),
 Timestamp('2012-03-01 14:25:00'),
 Timestamp('2012-03-01 14:30:00'),
 Timestamp('2012-03-01 14:35:00'),
 Timestamp('2012-03-01 14:40:00'),
 Timestamp('2012-03-01 14:45:00'),
 Timestamp('2012-03-01 14:50:00'),
 Timestamp('2012-03-01 14:55:00'),
 Timestamp('2012-03-01 15:00:00'),
 Timestamp('2012-03-01 15:05:00'),
 Timestamp('2012-03-01 15:10:00'),
 Timestamp('2012-03-01 15:15:00'),
 Timestamp('2012-03-01 15:20:00'),
 Timestamp('2012-03-01 15:25:00'),
 Timestamp('2012-03-01 15:30:00'),
 Timestamp('2012-03-01 15:35:00'),
 Timestamp('2012-03-01 15:40:00'),
 Timestamp('2012-03-01 15:45:00'),
 Timestamp('2012-03-01 15:50:00'),
 Timestamp('2012-03-01 15:55:00'),
 Timestamp('2012-03-01 16:00:00'),
 Timestamp('2012-03-01 16:05:00'),
 Timestamp('2012-03-01 16:10:00'),
 Timestamp('2012-03-01 16:15:00'),
 Timestamp('2012-03-01 16:20:00'),
 Timestamp('2012-03-01 16:25:00'),
 Timestamp('2012-03-01 16:30:00'),
 Timestamp('2012-03-01 16:35:00'),
 Timestamp('2012-03-01 16:40:00'),
 Timestamp('2012-03-01 16:45:00'),
 Timestamp('2012-03-01 16:50:00'),
 Timestamp('2012-03-01 16:55:00'),
 Timestamp('2012-03-01 17:00:00'),
 Timestamp('2012-03-01 17:05:00'),
 Timestamp('2012-03-01 17:10:00'),
 Timestamp('2012-03-01 17:15:00'),
 Timestamp('2012-03-01 17:20:00'),
 Timestamp('2012-03-01 17:25:00'),
 Timestamp('2012-03-01 17:30:00'),
 Timestamp('2012-03-01 17:35:00'),
 Timestamp('2012-03-01 17:40:00'),
 Timestamp('2012-03-01 17:45:00'),
 Timestamp('2012-03-01 17:50:00'),
 Timestamp('2012-03-01 17:55:00'),
 Timestamp('2012-03-01 18:00:00'),
 Timestamp('2012-03-01 18:05:00'),
 Timestamp('2012-03-01 18:10:00'),
 Timestamp('2012-03-01 18:15:00'),
 Timestamp('2012-03-01 18:20:00'),
 Timestamp('2012-03-01 18:25:00'),
 Timestamp('2012-03-01 18:30:00'),
 Timestamp('2012-03-01 18:35:00'),
 Timestamp('2012-03-01 18:40:00'),
 Timestamp('2012-03-01 18:45:00'),
 Timestamp('2012-03-01 18:50:00'),
 Timestamp('2012-03-01 18:55:00'),
 Timestamp('2012-03-01 19:00:00'),
 Timestamp('2012-03-01 19:05:00'),
 Timestamp('2012-03-01 19:10:00'),
 Timestamp('2012-03-01 19:15:00'),
 Timestamp('2012-03-01 19:20:00'),
 Timestamp('2012-03-01 19:25:00'),
 Timestamp('2012-03-01 19:30:00'),
 Timestamp('2012-03-01 19:35:00'),
 Timestamp('2012-03-01 19:40:00'),
 Timestamp('2012-03-01 19:45:00'),
 Timestamp('2012-03-01 19:50:00'),
 Timestamp('2012-03-01 19:55:00'),
 Timestamp('2012-03-01 20:00:00'),
 Timestamp('2012-03-01 20:05:00'),
 Timestamp('2012-03-01 20:10:00'),
 Timestamp('2012-03-01 20:15:00'),
 Timestamp('2012-03-01 20:20:00'),
 Timestamp('2012-03-01 20:25:00'),
 Timestamp('2012-03-01 20:30:00'),
 Timestamp('2012-03-01 20:35:00'),
 Timestamp('2012-03-01 20:40:00'),
 Timestamp('2012-03-01 20:45:00'),
 Timestamp('2012-03-01 20:50:00'),
 Timestamp('2012-03-01 20:55:00'),
 Timestamp('2012-03-01 21:00:00'),
 Timestamp('2012-03-01 21:05:00'),
 Timestamp('2012-03-01 21:10:00'),
 Timestamp('2012-03-01 21:15:00'),
 Timestamp('2012-03-01 21:20:00'),
 Timestamp('2012-03-01 21:25:00'),
 Timestamp('2012-03-01 21:30:00'),
 Timestamp('2012-03-01 21:35:00'),
 Timestamp('2012-03-01 21:40:00'),
 Timestamp('2012-03-01 21:45:00'),
 Timestamp('2012-03-01 21:50:00'),
 Timestamp('2012-03-01 21:55:00'),
 Timestamp('2012-03-01 22:00:00'),
 Timestamp('2012-03-01 22:05:00'),
 Timestamp('2012-03-01 22:10:00'),
 Timestamp('2012-03-01 22:15:00'),
 Timestamp('2012-03-01 22:20:00'),
 Timestamp('2012-03-01 22:25:00'),
 Timestamp('2012-03-01 22:30:00'),
 Timestamp('2012-03-01 22:35:00'),
 Timestamp('2012-03-01 22:40:00'),
 Timestamp('2012-03-01 22:45:00'),
 Timestamp('2012-03-01 22:50:00'),
 Timestamp('2012-03-01 22:55:00'),
 Timestamp('2012-03-01 23:00:00'),
 Timestamp('2012-03-01 23:05:00'),
 Timestamp('2012-03-01 23:10:00'),
 Timestamp('2012-03-01 23:15:00'),
 Timestamp('2012-03-01 23:20:00'),
 Timestamp('2012-03-01 23:25:00'),
 Timestamp('2012-03-01 23:30:00'),
 Timestamp('2012-03-01 23:35:00'),
 Timestamp('2012-03-01 23:40:00'),
 Timestamp('2012-03-01 23:45:00'),
 Timestamp('2012-03-01 23:50:00'),
 Timestamp('2012-03-01 23:55:00'),
 Timestamp('2012-03-02 00:00:00'),
 Timestamp('2012-03-02 00:05:00'),
 Timestamp('2012-03-02 00:10:00'),
 Timestamp('2012-03-02 00:15:00'),
 Timestamp('2012-03-02 00:20:00'),
 Timestamp('2012-03-02 00:25:00'),
 Timestamp('2012-03-02 00:30:00'),
 Timestamp('2012-03-02 00:35:00'),
 Timestamp('2012-03-02 00:40:00'),
 Timestamp('2012-03-02 00:45:00'),
 Timestamp('2012-03-02 00:50:00'),
 Timestamp('2012-03-02 00:55:00'),
 Timestamp('2012-03-02 01:00:00'),
 Timestamp('2012-03-02 01:05:00'),
 Timestamp('2012-03-02 01:10:00'),
 Timestamp('2012-03-02 01:15:00'),
 Timestamp('2012-03-02 01:20:00'),
 Timestamp('2012-03-02 01:25:00'),
 Timestamp('2012-03-02 01:30:00'),
 Timestamp('2012-03-02 01:35:00'),
 Timestamp('2012-03-02 01:40:00'),
 Timestamp('2012-03-02 01:45:00'),
 Timestamp('2012-03-02 01:50:00'),
 Timestamp('2012-03-02 01:55:00'),
 Timestamp('2012-03-02 02:00:00'),
 Timestamp('2012-03-02 02:05:00'),
 Timestamp('2012-03-02 02:10:00'),
 Timestamp('2012-03-02 02:15:00'),
 Timestamp('2012-03-02 02:20:00'),
 Timestamp('2012-03-02 02:25:00'),
 Timestamp('2012-03-02 02:30:00'),
 Timestamp('2012-03-02 02:35:00'),
 Timestamp('2012-03-02 02:40:00'),
 Timestamp('2012-03-02 02:45:00'),
 Timestamp('2012-03-02 02:50:00'),
 Timestamp('2012-03-02 02:55:00'),
 Timestamp('2012-03-02 03:00:00'),
 Timestamp('2012-03-02 03:05:00'),
 Timestamp('2012-03-02 03:10:00'),
 Timestamp('2012-03-02 03:15:00'),
 Timestamp('2012-03-02 03:20:00'),
 Timestamp('2012-03-02 03:25:00'),
 Timestamp('2012-03-02 03:30:00'),
 Timestamp('2012-03-02 03:35:00'),
 Timestamp('2012-03-02 03:40:00'),
 Timestamp('2012-03-02 03:45:00'),
 Timestamp('2012-03-02 03:50:00'),
 Timestamp('2012-03-02 03:55:00'),
 Timestamp('2012-03-02 04:00:00'),
 Timestamp('2012-03-02 04:05:00'),
 Timestamp('2012-03-02 04:10:00'),
 Timestamp('2012-03-02 04:15:00'),
 Timestamp('2012-03-02 04:20:00'),
 Timestamp('2012-03-02 04:25:00'),
 Timestamp('2012-03-02 04:30:00'),
 Timestamp('2012-03-02 04:35:00'),
 Timestamp('2012-03-02 04:40:00'),
 Timestamp('2012-03-02 04:45:00'),
 Timestamp('2012-03-02 04:50:00'),
 Timestamp('2012-03-02 04:55:00'),
 Timestamp('2012-03-02 05:00:00'),
 Timestamp('2012-03-02 05:05:00'),
 Timestamp('2012-03-02 05:10:00'),
 Timestamp('2012-03-02 05:15:00'),
 Timestamp('2012-03-02 05:20:00'),
 Timestamp('2012-03-02 05:25:00'),
 Timestamp('2012-03-02 05:30:00'),
 Timestamp('2012-03-02 05:35:00'),
 Timestamp('2012-03-02 05:40:00'),
 Timestamp('2012-03-02 05:45:00'),
 Timestamp('2012-03-02 05:50:00'),
 Timestamp('2012-03-02 05:55:00'),
 Timestamp('2012-03-02 06:00:00'),
 Timestamp('2012-03-02 06:05:00'),
 Timestamp('2012-03-02 06:10:00'),
 Timestamp('2012-03-02 06:15:00'),
 Timestamp('2012-03-02 06:20:00'),
 Timestamp('2012-03-02 06:25:00'),
 Timestamp('2012-03-02 06:30:00'),
 Timestamp('2012-03-02 06:35:00'),
 Timestamp('2012-03-02 06:40:00'),
 Timestamp('2012-03-02 06:45:00'),
 Timestamp('2012-03-02 06:50:00'),
 Timestamp('2012-03-02 06:55:00'),
 Timestamp('2012-03-02 07:00:00'),
 Timestamp('2012-03-02 07:05:00'),
 Timestamp('2012-03-02 07:10:00'),
 Timestamp('2012-03-02 07:15:00'),
 Timestamp('2012-03-02 07:20:00'),
 Timestamp('2012-03-02 07:25:00'),
 Timestamp('2012-03-02 07:30:00'),
 Timestamp('2012-03-02 07:35:00'),
 Timestamp('2012-03-02 07:40:00'),
 Timestamp('2012-03-02 07:45:00'),
 Timestamp('2012-03-02 07:50:00'),
 Timestamp('2012-03-02 07:55:00'),
 Timestamp('2012-03-02 08:00:00'),
 Timestamp('2012-03-02 08:05:00'),
 Timestamp('2012-03-02 08:10:00'),
 Timestamp('2012-03-02 08:15:00'),
 Timestamp('2012-03-02 08:20:00'),
 Timestamp('2012-03-02 08:25:00'),
 Timestamp('2012-03-02 08:30:00'),
 Timestamp('2012-03-02 08:35:00'),
 Timestamp('2012-03-02 08:40:00'),
 Timestamp('2012-03-02 08:45:00'),
 Timestamp('2012-03-02 08:50:00'),
 Timestamp('2012-03-02 08:55:00'),
 Timestamp('2012-03-02 09:00:00'),
 Timestamp('2012-03-02 09:05:00'),
 Timestamp('2012-03-02 09:10:00'),
 Timestamp('2012-03-02 09:15:00'),
 Timestamp('2012-03-02 09:20:00'),
 Timestamp('2012-03-02 09:25:00'),
 Timestamp('2012-03-02 09:30:00'),
 Timestamp('2012-03-02 09:35:00'),
 Timestamp('2012-03-02 09:40:00'),
 Timestamp('2012-03-02 09:45:00'),
 Timestamp('2012-03-02 09:50:00'),
 Timestamp('2012-03-02 09:55:00'),
 Timestamp('2012-03-02 10:00:00'),
 Timestamp('2012-03-02 10:05:00'),
 Timestamp('2012-03-02 10:10:00'),
 Timestamp('2012-03-02 10:15:00'),
 Timestamp('2012-03-02 10:20:00'),
 Timestamp('2012-03-02 10:25:00'),
 Timestamp('2012-03-02 10:30:00'),
 Timestamp('2012-03-02 10:35:00'),
 Timestamp('2012-03-02 10:40:00'),
 Timestamp('2012-03-02 10:45:00'),
 Timestamp('2012-03-02 10:50:00'),
 Timestamp('2012-03-02 10:55:00'),
 Timestamp('2012-03-02 11:00:00'),
 Timestamp('2012-03-02 11:05:00'),
 Timestamp('2012-03-02 11:10:00'),
 Timestamp('2012-03-02 11:15:00'),
 Timestamp('2012-03-02 11:20:00'),
 Timestamp('2012-03-02 11:25:00'),
 Timestamp('2012-03-02 11:30:00'),
 Timestamp('2012-03-02 11:35:00'),
 Timestamp('2012-03-02 11:40:00'),
 Timestamp('2012-03-02 11:45:00'),
 Timestamp('2012-03-02 11:50:00'),
 Timestamp('2012-03-02 11:55:00'),
 Timestamp('2012-03-02 12:00:00'),
 Timestamp('2012-03-02 12:05:00'),
 Timestamp('2012-03-02 12:10:00'),
 Timestamp('2012-03-02 12:15:00'),
 Timestamp('2012-03-02 12:20:00'),
 Timestamp('2012-03-02 12:25:00'),
 Timestamp('2012-03-02 12:30:00'),
 Timestamp('2012-03-02 12:35:00'),
 Timestamp('2012-03-02 12:40:00'),
 Timestamp('2012-03-02 12:45:00'),
 Timestamp('2012-03-02 12:50:00'),
 Timestamp('2012-03-02 12:55:00'),
 Timestamp('2012-03-02 13:00:00'),
 Timestamp('2012-03-02 13:05:00'),
 Timestamp('2012-03-02 13:10:00'),
 Timestamp('2012-03-02 13:15:00'),
 Timestamp('2012-03-02 13:20:00'),
 Timestamp('2012-03-02 13:25:00'),
 Timestamp('2012-03-02 13:30:00'),
 Timestamp('2012-03-02 13:35:00'),
 Timestamp('2012-03-02 13:40:00'),
 Timestamp('2012-03-02 13:45:00'),
 Timestamp('2012-03-02 13:50:00'),
 Timestamp('2012-03-02 13:55:00'),
 Timestamp('2012-03-02 14:00:00'),
 Timestamp('2012-03-02 14:05:00'),
 Timestamp('2012-03-02 14:10:00'),
 Timestamp('2012-03-02 14:15:00'),
 Timestamp('2012-03-02 14:20:00'),
 Timestamp('2012-03-02 14:25:00'),
 Timestamp('2012-03-02 14:30:00'),
 Timestamp('2012-03-02 14:35:00'),
 Timestamp('2012-03-02 14:40:00'),
 Timestamp('2012-03-02 14:45:00'),
 Timestamp('2012-03-02 14:50:00'),
 Timestamp('2012-03-02 14:55:00'),
 Timestamp('2012-03-02 15:00:00'),
 Timestamp('2012-03-02 15:05:00'),
 Timestamp('2012-03-02 15:10:00'),
 Timestamp('2012-03-02 15:15:00'),
 Timestamp('2012-03-02 15:20:00'),
 Timestamp('2012-03-02 15:25:00'),
 Timestamp('2012-03-02 15:30:00'),
 Timestamp('2012-03-02 15:35:00'),
 Timestamp('2012-03-02 15:40:00'),
 Timestamp('2012-03-02 15:45:00'),
 Timestamp('2012-03-02 15:50:00'),
 Timestamp('2012-03-02 15:55:00'),
 Timestamp('2012-03-02 16:00:00'),
 Timestamp('2012-03-02 16:05:00'),
 Timestamp('2012-03-02 16:10:00'),
 Timestamp('2012-03-02 16:15:00'),
 Timestamp('2012-03-02 16:20:00'),
 Timestamp('2012-03-02 16:25:00'),
 Timestamp('2012-03-02 16:30:00'),
 Timestamp('2012-03-02 16:35:00'),
 Timestamp('2012-03-02 16:40:00'),
 Timestamp('2012-03-02 16:45:00'),
 Timestamp('2012-03-02 16:50:00'),
 Timestamp('2012-03-02 16:55:00'),
 Timestamp('2012-03-02 17:00:00'),
 Timestamp('2012-03-02 17:05:00'),
 Timestamp('2012-03-02 17:10:00'),
 Timestamp('2012-03-02 17:15:00'),
 Timestamp('2012-03-02 17:20:00'),
 Timestamp('2012-03-02 17:25:00'),
 Timestamp('2012-03-02 17:30:00'),
 Timestamp('2012-03-02 17:35:00'),
 Timestamp('2012-03-02 17:40:00'),
 Timestamp('2012-03-02 17:45:00'),
 Timestamp('2012-03-02 17:50:00'),
 Timestamp('2012-03-02 17:55:00'),
 Timestamp('2012-03-02 18:00:00'),
 Timestamp('2012-03-02 18:05:00'),
 Timestamp('2012-03-02 18:10:00'),
 Timestamp('2012-03-02 18:15:00'),
 Timestamp('2012-03-02 18:20:00'),
 Timestamp('2012-03-02 18:25:00'),
 Timestamp('2012-03-02 18:30:00'),
 Timestamp('2012-03-02 18:35:00'),
 Timestamp('2012-03-02 18:40:00'),
 Timestamp('2012-03-02 18:45:00'),
 Timestamp('2012-03-02 18:50:00'),
 Timestamp('2012-03-02 18:55:00'),
 Timestamp('2012-03-02 19:00:00'),
 Timestamp('2012-03-02 19:05:00'),
 Timestamp('2012-03-02 19:10:00'),
 Timestamp('2012-03-02 19:15:00'),
 Timestamp('2012-03-02 19:20:00'),
 Timestamp('2012-03-02 19:25:00'),
 Timestamp('2012-03-02 19:30:00'),
 Timestamp('2012-03-02 19:35:00'),
 Timestamp('2012-03-02 19:40:00'),
 Timestamp('2012-03-02 19:45:00'),
 Timestamp('2012-03-02 19:50:00'),
 Timestamp('2012-03-02 19:55:00'),
 Timestamp('2012-03-02 20:00:00'),
 Timestamp('2012-03-02 20:05:00'),
 Timestamp('2012-03-02 20:10:00'),
 Timestamp('2012-03-02 20:15:00'),
 Timestamp('2012-03-02 20:20:00'),
 Timestamp('2012-03-02 20:25:00'),
 Timestamp('2012-03-02 20:30:00'),
 Timestamp('2012-03-02 20:35:00'),
 Timestamp('2012-03-02 20:40:00'),
 Timestamp('2012-03-02 20:45:00'),
 Timestamp('2012-03-02 20:50:00'),
 Timestamp('2012-03-02 20:55:00'),
 Timestamp('2012-03-02 21:00:00'),
 Timestamp('2012-03-02 21:05:00'),
 Timestamp('2012-03-02 21:10:00'),
 Timestamp('2012-03-02 21:15:00'),
 Timestamp('2012-03-02 21:20:00'),
 Timestamp('2012-03-02 21:25:00'),
 Timestamp('2012-03-02 21:30:00'),
 Timestamp('2012-03-02 21:35:00'),
 Timestamp('2012-03-02 21:40:00'),
 Timestamp('2012-03-02 21:45:00'),
 Timestamp('2012-03-02 21:50:00'),
 Timestamp('2012-03-02 21:55:00'),
 Timestamp('2012-03-02 22:00:00'),
 Timestamp('2012-03-02 22:05:00'),
 Timestamp('2012-03-02 22:10:00'),
 Timestamp('2012-03-02 22:15:00'),
 Timestamp('2012-03-02 22:20:00'),
 Timestamp('2012-03-02 22:25:00'),
 Timestamp('2012-03-02 22:30:00'),
 Timestamp('2012-03-02 22:35:00'),
 Timestamp('2012-03-02 22:40:00'),
 Timestamp('2012-03-02 22:45:00'),
 Timestamp('2012-03-02 22:50:00'),
 Timestamp('2012-03-02 22:55:00'),
 Timestamp('2012-03-02 23:00:00'),
 Timestamp('2012-03-02 23:05:00'),
 Timestamp('2012-03-02 23:10:00'),
 Timestamp('2012-03-02 23:15:00'),
 Timestamp('2012-03-02 23:20:00'),
 Timestamp('2012-03-02 23:25:00'),
 Timestamp('2012-03-02 23:30:00'),

In [39]:
date_range = pd.date_range(datetime_idx[0], datetime_idx[-1], freq='5T')
df = df.reindex(index=date_range)
df

,773869,767541,767542,717447,717446,717445,773062,767620,737529,717816,...,772167,769372,774204,769806,717590,717592,717595,772168,718141,769373
2012-03-01 00:00:00,64.375000,67.625000,67.125000,61.500000,66.875000,68.750000,65.125000,67.125000,59.625000,62.750000,...,45.625000,65.500000,64.500000,66.428571,66.875000,59.375000,69.000000,59.250000,69.000000,61.875000
2012-03-01 00:05:00,62.666667,68.555556,65.444444,62.444444,64.444444,68.111111,65.000000,65.000000,57.444444,63.333333,...,50.666667,69.875000,66.666667,58.555556,62.000000,61.111111,64.444444,55.888889,68.444444,62.875000
2012-03-01 00:10:00,64.000000,63.750000,60.000000,59.000000,66.500000,66.250000,64.500000,64.250000,63.875000,65.375000,...,44.125000,69.000000,56.500000,59.250000,68.125000,62.500000,65.625000,61.375000,69.857143,62.000000
2012-03-01 00:15:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2012-03-01 00:20:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2012-06-27 23:35:00,65.000000,65.888889,68.555556,61.666667,0.000000,54.555556,62.444444,63.333333,59.222222,65.333333,...,52.888889,69.000000,65.111111,55.666667,66.333333,62.444444,66.777778,64.888889,69.666667,62.333333
2012-06-27 23:40:00,61.375000,65.625000,66.500000,62.750000,0.000000,50.500000,62.000000,67.000000,65.250000,67.125000,...,54.000000,69.250000,60.125000,60.500000,67.250000,59.375000,66.000000,61.250000,69.000000,62.000000
2012-06-27 23:45:00,67.000000,59.666667,69.555556,61.000000,0.000000,44.777778,64.222222,63.777778,59.777778,57.666667,...,51.333333,67.888889,64.333333,57.000000,66.000000,62.666667,68.666667,63.333333,67.444444,61.222222
2012-06-27 23:50:00,66.750000,62.250000,66.000000,59.625000,0.000000,53.000000,64.285714,64.125000,60.875000,66.250000,...,51.125000,69.375000,61.625000,60.500000,65.625000,66.375000,69.500000,63.000000,67.875000,63.500000
2012-06-27 23:55:00,65.111111,66.888889,66.777778,61.222222,0.000000,49.555556,65.777778,65.111111,63.000000,61.666667,...,56.000000,67.444444,64.888889,60.888889,64.222222,66.444444,68.444444,63.555556,68.666667,61.777778

In [40]:
mask = ~np.isnan(df.values)
mask

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [3]:
datetime_idx = sorted(df.index)
date_range = pd.date_range(datetime_idx[0], datetime_idx[-1], freq='5T')
df = df.reindex(index=date_range)
df

,773869,767541,767542,717447,717446,717445,773062,767620,737529,717816,...,772167,769372,774204,769806,717590,717592,717595,772168,718141,769373
2012-03-01 00:00:00,64.375000,67.625000,67.125000,61.500000,66.875000,68.750000,65.125000,67.125000,59.625000,62.750000,...,45.625000,65.500000,64.500000,66.428571,66.875000,59.375000,69.000000,59.250000,69.000000,61.875000
2012-03-01 00:05:00,62.666667,68.555556,65.444444,62.444444,64.444444,68.111111,65.000000,65.000000,57.444444,63.333333,...,50.666667,69.875000,66.666667,58.555556,62.000000,61.111111,64.444444,55.888889,68.444444,62.875000
2012-03-01 00:10:00,64.000000,63.750000,60.000000,59.000000,66.500000,66.250000,64.500000,64.250000,63.875000,65.375000,...,44.125000,69.000000,56.500000,59.250000,68.125000,62.500000,65.625000,61.375000,69.857143,62.000000
2012-03-01 00:15:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2012-03-01 00:20:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2012-06-27 23:35:00,65.000000,65.888889,68.555556,61.666667,0.000000,54.555556,62.444444,63.333333,59.222222,65.333333,...,52.888889,69.000000,65.111111,55.666667,66.333333,62.444444,66.777778,64.888889,69.666667,62.333333
2012-06-27 23:40:00,61.375000,65.625000,66.500000,62.750000,0.000000,50.500000,62.000000,67.000000,65.250000,67.125000,...,54.000000,69.250000,60.125000,60.500000,67.250000,59.375000,66.000000,61.250000,69.000000,62.000000
2012-06-27 23:45:00,67.000000,59.666667,69.555556,61.000000,0.000000,44.777778,64.222222,63.777778,59.777778,57.666667,...,51.333333,67.888889,64.333333,57.000000,66.000000,62.666667,68.666667,63.333333,67.444444,61.222222
2012-06-27 23:50:00,66.750000,62.250000,66.000000,59.625000,0.000000,53.000000,64.285714,64.125000,60.875000,66.250000,...,51.125000,69.375000,61.625000,60.500000,65.625000,66.375000,69.500000,63.000000,67.875000,63.500000
2012-06-27 23:55:00,65.111111,66.888889,66.777778,61.222222,0.000000,49.555556,65.777778,65.111111,63.000000,61.666667,...,56.000000,67.444444,64.888889,60.888889,64.222222,66.444444,68.444444,63.555556,68.666667,61.777778

In [4]:
mask = ~np.isnan(df.values)
mask

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])